#include "Instruction.h"
#include "PRNT.h"
#include "PRNTV.h"
#include "PRNTM.h"
#include "CALL.h"
#include "RET.h"
#include "Segment.h"
#include "ConditionJMP.h"
#include "JMP.h"
#include "JMPIF.h"
#include "MOV.h"
#include "VAR.h"

#include "INC.h"
#include "DEC.h"
